---
- name: Wait initial admin password is appear
  wait_for:
    path: /var/lib/jenkins/secrets/initialAdminPassword
#
- name: Get initial admin password
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: initial_password
#
- name: Initial admin password is
  debug:
    msg: "{{ initial_password.stdout }}"
#
- name: Access to complete the installation
  debug:
    msg: "http://{{ ansible_default_ipv4.address }}:8080"
...
